/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Auto-généré depuis le titre si laissé vide.
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Ordre d'affichage (croissant) sur l'accueil et pour « projet suivant ».
   */
  order?: number | null;
  /**
   * Date de réalisation du projet.
   */
  date?: string | null;
  /**
   * Eyebrow mono, ex. « SaaS · Data-viz ». Requis pour publier.
   */
  category?: string | null;
  /**
   * Accroche affichée sous le titre du case study. Requis pour publier.
   */
  lead?: string | null;
  /**
   * Description courte de la ligne projet sur l'accueil.
   */
  cardDescription?: string | null;
  /**
   * Tags affichés sur l’accueil et dans la meta strip « Stack ».
   */
  technologies?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    role?: string | null;
    /**
     * Texte libre, ex. « 2022 — 24 ».
     */
    year?: string | null;
    /**
     * Texte libre, ex. « En continu ».
     */
    duration?: string | null;
  };
  /**
   * Visuel hero. Si vide, un placeholder rayé est affiché.
   */
  cover?: (number | null) | Media;
  /**
   * Galerie (1 large + le reste). Si vide, placeholders rayés.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  context?: {
    heading?: string | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  challenge?: {
    heading?: string | null;
    /**
     * Liste numérotée (01, 02, 03…).
     */
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  approach?: {
    heading?: string | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Liste à puces ↳.
     */
    points?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  results?: {
    heading?: string | null;
    stats?:
      | {
          /**
           * Valeur du compteur, décimales avec « . » (ex. « 2.1 »).
           */
          value: string;
          /**
           * Suffixe accentué (%, +, fps, s…).
           */
          suffix?: string | null;
          caption: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Champ libre (non affiché par le thème actuel).
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  order?: T;
  date?: T;
  category?: T;
  lead?: T;
  cardDescription?: T;
  technologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        role?: T;
        year?: T;
        duration?: T;
      };
  cover?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  context?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  challenge?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  approach?:
    | T
    | {
        heading?: T;
        body?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  results?:
    | T
    | {
        heading?: T;
        stats?:
          | T
          | {
              value?: T;
              suffix?: T;
              caption?: T;
              id?: T;
            };
      };
  description?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  identity: {
    name: string;
    role?: string | null;
    /**
     * Sigle nav, ex. « EB ».
     */
    brand?: string | null;
    /**
     * ex. « .dev ».
     */
    brandSuffix?: string | null;
    location?: string | null;
    year?: string | null;
    email?: string | null;
  };
  hero?: {
    status?: string | null;
    /**
     * Par défaut : le nom.
     */
    titleLine1?: string | null;
    /**
     * Mot en contour, ex. « Frontend ».
     */
    titleOutline?: string | null;
    /**
     * Mot en accent, ex. « Senior ».
     */
    titleAccent?: string | null;
    /**
     * Accroche. Gras + couleurs accent/atténué disponibles.
     */
    lead?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    scrollLabel?: string | null;
  };
  marquee?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  about?: {
    eyebrow?: string | null;
    /**
     * Paragraphes. Gras + couleurs accent/atténué disponibles.
     */
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    stats?:
      | {
          value: string;
          suffix?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  projects?: {
    eyebrow?: string | null;
    title?: string | null;
  };
  experience?: {
    eyebrow?: string | null;
    title?: string | null;
    items?:
      | {
          period?: string | null;
          role?: string | null;
          company?: string | null;
          points?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  stack?: {
    eyebrow?: string | null;
    title?: string | null;
    cards?:
      | {
          /**
           * ex. « /A ».
           */
          n?: string | null;
          category: string;
          skills?:
            | {
                name: string;
                level?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    eyebrow?: string | null;
    lines?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * ex. « ensemble ↗ ».
     */
    linkText?: string | null;
    sub?: string | null;
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  footer?: {
    copyright?: string | null;
    tagline?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  identity?:
    | T
    | {
        name?: T;
        role?: T;
        brand?: T;
        brandSuffix?: T;
        location?: T;
        year?: T;
        email?: T;
      };
  hero?:
    | T
    | {
        status?: T;
        titleLine1?: T;
        titleOutline?: T;
        titleAccent?: T;
        lead?: T;
        scrollLabel?: T;
      };
  marquee?:
    | T
    | {
        item?: T;
        id?: T;
      };
  about?:
    | T
    | {
        eyebrow?: T;
        body?: T;
        stats?:
          | T
          | {
              value?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
      };
  projects?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  experience?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              period?: T;
              role?: T;
              company?: T;
              points?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  stack?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        cards?:
          | T
          | {
              n?: T;
              category?: T;
              skills?:
                | T
                | {
                    name?: T;
                    level?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  contact?:
    | T
    | {
        eyebrow?: T;
        lines?:
          | T
          | {
              text?: T;
              id?: T;
            };
        linkText?: T;
        sub?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        copyright?: T;
        tagline?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}